controller:
  metrics:
    enabled: true
configs:
  cm:
    application.resourceTrackingMethod: annotation
  params:
    application.namespaces: '*'
repoServer:
  metrics:
    service:
      labels:
        prometheus: main
server:
  metrics:
    service:
      labels:
        prometheus: main