extraScrapeConfigs: |
  - job_name: argocd-controller
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets:
          - argocd-application-controller-metrics.argocd.svc.cluster.local:8082

  - job_name: go-http-server
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets:
          - origoss-task-service.webserver.svc.cluster.local:8080
