extraScrapeConfigs: |
  - job_name: argocd-controller
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets:
          - argocd-application-controller-metrics.argocd.svc.cluster.local:8082

  - job_name: argocd-server
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets:
          - argocd-server-metrics.argocd.svc.cluster.local:8083

  - job_name: argocd-repo-server
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets:
          - argocd-repo-server.argocd.svc.cluster.local:8084

  - job_name: argocd-applicationset-controller
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets:
          - argocd-applicationset-controller.argocd.svc.cluster.local:8080

